### ISSUE TITLE
Add required LICENSE and COPYING files

### ISSUE THREAD

**Issue by IAmTrial** [cyhyraethz/d2-sp-mods#1]
The two files SGD2FreeRes.dll and SGD2FreeDisplayFix.dll are both released under the Affero General Public License (AGPL), version 3 or greater. I've noticed that this repository currently does not contain the associated COPYING and LICENSE files, which is a requirement under the AGPL. [Section 4 of the AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html) states that you must "give all recipients a copy of this License along with the Program."

To fix this, you just need to store the files (each separate LICENSE and COPYING files from each project) in the repository.

**Comment by cyhyraethz** [comment]
Thanks for letting me know. My apologies for the oversight.

I added the files to the ModPack/docs directory, where the README and CHANGELOG files are. Is that good, or should I put them in the ModPack directory where the DLLs are instead?

**Comment by IAmTrial** [comment]
They can be in the ModPack/docs directory. Thanks for the quick response!
